public class WhatsAppIntegrationConstant {

    public static final String SECURITY_ACCESS_TOKEN = 'EAATcXHZAUEJQBO9IZCZB9jTHtI7P4m5C0QAoTfgZC1f0zbReqZBDmjUy2ZAwV19y53PrUaPqMT9dHKFMFQ6rG7xI3dG4koSofpkr8cDPAEMEQ9zZB0AQ46pkkiZBUMu24ZAtisGZCQJQ5ZBCqAkiMQVkNHwoNyyMZBhMUm36HOM86GvnjWmj8MZAE9gZCWUvoyRmXrfTHPNPyqYhkYhooQNEvfcuBEcjhXu8XfkyxgvTUnCTEZD';  
    public static final String API_URL = 'https://graph.facebook.com/v18.0/242862368912299/messages';  
}