public class WhatsAppIntegrationConstant {

    public static final String SECURITY_ACCESS_TOKEN = 'EAATcXHZAUEJQBO7nZBidw63TDujaXMTXYyrDJTBUJt0hthTE6bVtErtKffrZB6GUmzSpvGckZCWYO4ksTmDIV2fgZB1qBrY4Os7Fq402nHoZCtn3dDxJYAXlnUxoyglTlcuilMHYpFjCZAbub4sxctbGHlNbHlZAoT9GZCbBZBw2zBDKQvtv4leZBZCSplfOGM6ZCTccN';  
    public static final String API_URL = 'https://graph.facebook.com/v18.0/242862368912299/messages';  
    public static final String POST_METHOD = 'POST';
}